### ISSUE TITLE
Assets aren't uploaded? 

### ISSUE THREAD

**Issue by Rawrly85** [Jules-Bens-Aa/JB2A_DnD5e#1]
After installing the module, I don't see any images where they are supposed to be located.

![image](https://user-images.githubusercontent.com/53245027/97763095-d20fd880-1ac7-11eb-8dbd-f1cdfc3abc7d.png)

**Comment by BenIsWassily** [comment]
That's weird ! I'm looking at it right now. Thanks for the warning.

**Comment by BenIsWassily** [comment]
From my side, by installing it from the Foundry I have no issue.
Did you install the module manually or from Foundry ? How did you do it exactly ?

**Comment by Rawrly85** [comment]
From Foundry, might be on my end. I don't manage the server, so ill ask the owner to check the logs. Maybe there is a permission issue not allowing the images to be saved when installing.

**Comment by BenIsWassily** [comment]
Maybe I'm wrong but your window is an "**Image Browser**".
It should be "**Image or video Browser**"
It may be the reason why you don't see any assets. They aren't images but videos. _(see screenshot below)_

Do you have the lastest version of Foundry ?
If not, which version do you have ?
It should work with tiles and tokens, but **not for portraits** as it does not accept video format. To my knowledge, for portaits to be animated, the file format should be WebP or Gif (not sure for the last one).

![Capture d’écran 2020-10-31 004011](https://user-images.githubusercontent.com/34525955/97765255-b03b4380-1b11-11eb-8e66-57d65ac06207.jpg)

**Comment by BenIsWassily** [comment]
Are you try to apply the animated assets to a token ?

**Comment by Rawrly85** [comment]
Ah, that makes sense then maybe im misunderstanding the usage. I was trying to assign this to both a circle template or an actor token but both don't have the image option. On on the latest release version of foundry 0.7.5.

**Comment by BenIsWassily** [comment]
If you do the exact same steps like shown in the videos on the main page, can you see the assets in the browser ?

**Comment by BenIsWassily** [comment]
Sorry, I wasn't totally accurate ealier.
The animated assets work with : 
- Tiles
- Templates
- and tokens

And they are not currently working on portraits.

**Comment by Rawrly85** [comment]
My bad, it seems like I may have selected portraits when trying to do the actor route

**Comment by BenIsWassily** [comment]
No problem, it happens ! 
Your issue helped me to realize that I didn't explained on the main page how to use our assets with the templates.
And that I should had something about portraits.

> These are amazing btw!


Thanks a lot !

I'm losing the issue, then
