### ISSUE TITLE
No method of contact?

### ISSUE THREAD

**Issue by Pentazer** [Jules-Bens-Aa/JB2A_DnD5e#15]
I'm trying to find a way to ask a question of the dev regarding the paid version, but I do not use discord as it social media. How do I get in touch by more reasonable and respectable means?

**Comment by Jules-Bens-Aa** [comment]
There are two ways to contact us directly :
-  Our [Discord server](https://discord.gg/gmd8MAPX4m) 
or
- By logging in on our [Patreon](https://www.patreon.com/JB2A) and sending us a message by using this button.

![image](https://github.com/Jules-Bens-Aa/JB2A_DnD5e/assets/73002638/a398f353-fec8-42cd-a02e-d55090abb326)
