### ISSUE TITLE
Inconsistent Sequencer database entries between free and Patreon versions

### ISSUE THREAD

**Issue by cirrahn** [Jules-Bens-Aa/JB2A_DnD5e#16]
Some animations are registered at different Sequencer database paths between the free and Patreon versions.

For example:

```
# free
jb2a.melee_attack.03.trail.greatsword

# patreon
jb2a.melee_attack.03.greatsword
```

(The example animation is listed as `jb2a.melee_attack.03.greatsword` in the Asset Viewer https://library.jb2a.com/#Melee%20Attacks%20-%20Group%2003 )

This issue affects multiple animations under `jb2a.melee_attack.03`, where it looks like the `trail` object has been set as the parent of other objects.

See: https://github.com/Jules-Bens-Aa/JB2A_DnD5e/blob/main/scripts/jb2a_sequencer.js#L2742

**Comment by Gazkhan** [comment]
Thanks a lot for the issue and apologies for the delay, we're not used to having issues on Github! 😅 
It should be fixed next release v0.6.9 👍
