### ISSUE TITLE
error and not update

### ISSUE THREAD

**Issue by cnutenor** [Jules-Bens-Aa/JB2A_DnD5e#2]
hi, when i try to update, appears a error. Thanks!

**Comment by mascent** [comment]
I have the same issue, but I think it's an non issue. The new version isn't released yet, but the module.json already points to the new version _0.5_. It should work if the new version is released.

**Comment by Jules-Bens-Aa** [comment]
Hum, I released the new version, so I messed up somewhere. I'm investigating right now.

**Comment by Jules-Bens-Aa** [comment]
Oh, I just realized that your posts was 5/6 hours old. Sorry for the delay then.
It should work right now. I just updated from the 0.0.4 to the 0.0.5 on my side without any issues.

Keep me in touch, if you still have a problem when updating the module.
I'll close the issue once you give my the green light.

**Comment by mascent** [comment]
It works now 😊 you can close the issue.
