### ISSUE TITLE
Failure to install via mod store

### ISSUE THREAD

**Issue by kelanel** [Jules-Bens-Aa/JB2A_DnD5e#4]
Download succeeds but then crashes during install around 56%. Error:

FoundryVTT | 2021-01-14 21:17:33 | [info] Installing Package - 56%
(node:10) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/data/foundryvtt/Data/modules/JB2A_DnD5e/Library/4th_Level/Wall_of_fire'
    at Object.mkdirSync (fs.js:914:3)
    at Function.sync (/opt/foundryvtt/resources/app/node_modules/mkdirp/index.js:72:13)
    at Function.mkdir (/opt/foundryvtt/resources/app/dist/files/files.js:1:10015)
    at Function._extractEntry (/opt/foundryvtt/resources/app/dist/files/files.js:1:8634)
    at _0x25bdec (/opt/foundryvtt/resources/app/dist/files/files.js:1:7528)
    at ZipFile.<anonymous> (/opt/foundryvtt/resources/app/dist/files/files.js:1:6825)
    at ZipFile.emit (events.js:315:20)
    at ZipFile.EventEmitter.emit (domain.js:482:12)
    at /opt/foundryvtt/resources/app/node_modules/yauzl/index.js:428:12
    at /opt/foundryvtt/resources/app/node_modules/yauzl/index.js:631:5
(node:10) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kelanel** [comment]
Looks like the wall of fire folders with upper/lower case conflict inside my windows based docker image. Can we just remove the extra folder and leave the readme in 4th level folder?

**Comment by Jules-Bens-Aa** [comment]
Yep, I'll fix that later today. Thanks for the report ! 
I don't understand though, this folder shouldn't exist Oo

**Comment by Jules-Bens-Aa** [comment]
Updated the patch.
Did it resolved your issue ?

**Comment by kelanel** [comment]
I copied the folder manually from github so not sure. I'll delete and redownload the mod later

**Comment by Jules-Bens-Aa** [comment]
I'll leave the issue open until your confirmation.
No rush :)

**Comment by kelanel** [comment]
That worked!
