### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by YuriAlessandro** [Jules-Bens-Aa/JB2A_DnD5e#5]
I'm getting this error since the last update and cat install the module. It stuck when it reach 100% on install.

![image](https://user-images.githubusercontent.com/14967048/116764930-32d98880-a9f9-11eb-82d4-49f20358382e.png)

**Comment by Jules-Bens-Aa** [comment]
Have you tried this :
 - Shutdown your server
 - Go inside you `Data/Modules` folder (to find this folder on your computer read this https://foundryvtt.com/article/configuration/#where-user-data)
 - Look for a **file** called `JB2A_DnD5e.zip` and erase it.
 - Look for a **folder** called `JB2A_DnD5e` and erase it.
 - Start your server and install the module again.

**Comment by YuriAlessandro** [comment]
I've tried this but not worked, same problem :/

I'll try to just install it manually (if this is a thing)

**Comment by YuriAlessandro** [comment]
Yeah, install it manually and worked. Thanks for the response, anyway

**Comment by Jules-Bens-Aa** [comment]
Glad you could resolve your issue. I don't really understand why this is happening from time to time. It happened to me a couple of times with other modules, and I didn't found the reason behind this "stuck at 100%" thing.
If it is all good for you, I'm going to close this issue.

**Comment by Jules-Bens-Aa** [comment]
Closing the issue.
