### ISSUE TITLE
Add a LICENSE to the project

### ISSUE THREAD

**Issue by p4535992** [Jules-Bens-Aa/JB2A_DnD5e#8]
Hi, I was preparing a module for foundryvtt, but to be sure which license to apply (as even if to a small extent) use some of your animations and I wanted you to add a license on the project (If possible the MIT license is preferable, but it is your choice).

**Comment by Jules-Bens-Aa** [comment]
Thanks for heads up ! 
We thought we did but the link was broken. here is the [license](https://creativecommons.org/choose/results-one?license_code=by-nc-sa&amp;jurisdiction=&amp;version=4.0&amp;lang=en) for our assets. If you have any questions fell free to get it touch with us.
We have a [Discord server](https://discord.com/invite/gmd8MAPX4m) if you want a quick response.

**Comment by p4535992** [comment]
Ty man!
